// Data for the (secret) /changelog page.
// Generated from this repo's real git history — one release per commit on main.
// Line counts exclude package-lock.json and binary files (images, PDFs).

export type ChangelogBadge = 'new' | 'improved' | 'fixed' | 'milestone';

export interface ChangelogEntry {
  version: string;
  badge: ChangelogBadge;
  day: string; // ISO date (Pacific Time), used for grouping
  time: string | null; // e.g. "11:26 AM PDT" — null hides the time (milestone)
  author: string;
  adds: number;
  dels: number;
  title: string;
  bullets: string[];
}

export const DEV_START = '2025-08-12T07:32:24-07:00';

// Oldest → newest. The page renders newest first.
export const changelogEntries: ChangelogEntry[] = [
  {
    version: '0.1.0',
    badge: 'milestone',
    day: '2025-08-12',
    time: null,
    author: 'Eve Bouffard',
    adds: 873,
    dels: 0,
    title: 'The Social Radars site first goes live',
    bullets: [
      'A single-page landing site for the podcast: hero, episodes, hosts, and about — all hand-written HTML.',
      'Episode art for the first interviews — Sam Altman, Drew Houston, Ron Conway, and more.',
      'Two variants of the page shipped side by side while the design settled.',
    ],
  },
  {
    version: '1.0',
    badge: 'improved',
    day: '2025-08-12',
    time: '8:04 AM PDT',
    author: 'Eve Bouffard',
    adds: 198,
    dels: 83,
    title: 'Buttons standardized on the orange theme',
    bullets: [
      'Every button now shares the same orange treatment and proportions across both page variants.',
      'First pass at a consistent visual language for calls to action.',
    ],
  },
  {
    version: '1.1',
    badge: 'improved',
    day: '2025-10-08',
    time: '1:58 PM PDT',
    author: 'Eve Bouffard',
    adds: 1053,
    dels: 932,
    title: 'Episode cards redesigned',
    bullets: [
      'New design and layout for the episode cards on the landing page.',
      'Photos added for the How It Started era — the first YC batch, young founders, and more.',
      'Old placeholder assets cleared out.',
    ],
  },
  {
    version: '1.2',
    badge: 'new',
    day: '2025-10-08',
    time: '2:40 PM PDT',
    author: 'Eve Bouffard',
    adds: 99,
    dels: 0,
    title: 'Deploy configuration lands',
    bullets: [
      'Netlify and Vercel configs so the site can ship to real hosting.',
      'Security headers and year-long caching for images.',
      'A proper .gitignore for the repo.',
    ],
  },
  {
    version: '1.3',
    badge: 'new',
    day: '2025-10-14',
    time: '6:30 PM PDT',
    author: 'Eve Bouffard',
    adds: 260,
    dels: 305,
    title: 'Dynamic episode system',
    bullets: [
      'Episodes now come from a single data file instead of hand-edited HTML.',
      'One source of truth for every episode — groundwork for the React rebuild.',
    ],
  },
  {
    version: '1.4',
    badge: 'fixed',
    day: '2025-10-14',
    time: '6:36 PM PDT',
    author: 'Eve Bouffard',
    adds: 1908,
    dels: 99,
    title: 'Images moved to public/ for Vercel',
    bullets: [
      'Every image now lives in public/ with paths Vercel can actually serve.',
      'Project docs added: README and installation guide.',
    ],
  },
  {
    version: '1.5',
    badge: 'improved',
    day: '2025-10-14',
    time: '6:58 PM PDT',
    author: 'Eve Bouffard',
    adds: 11,
    dels: 1404,
    title: 'React-only cleanup',
    bullets: [
      'The old static HTML pages are gone — the site is now React + TypeScript only.',
      'Duplicate images and the legacy episodes data file removed. 1,404 lines of dead weight deleted.',
    ],
  },
  {
    version: '1.6',
    badge: 'fixed',
    day: '2025-10-14',
    time: '7:10 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: 'Hero image path on Vercel',
    bullets: ['Hero image path corrected so it resolves in production.'],
  },
  {
    version: '1.7',
    badge: 'fixed',
    day: '2025-10-14',
    time: '7:11 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: 'Hero background swapped to the Jessica image',
    bullets: ['Hero background now uses jessica-hero-image.png.'],
  },
  {
    version: '1.8',
    badge: 'new',
    day: '2025-10-14',
    time: '7:15 PM PDT',
    author: 'Eve Bouffard',
    adds: 13,
    dels: 0,
    title: 'Dark overlay on the hero',
    bullets: ['A dark overlay on the hero image so the title stays readable on any screen.'],
  },
  {
    version: '1.9',
    badge: 'improved',
    day: '2025-10-14',
    time: '7:16 PM PDT',
    author: 'Eve Bouffard',
    adds: 79,
    dels: 5,
    title: 'Favicon switched to the logo watermark',
    bullets: [
      'The browser tab now shows the Social Radars watermark.',
      'An SVG version of the watermark added alongside the PNG.',
    ],
  },
  {
    version: '1.10',
    badge: 'improved',
    day: '2025-10-14',
    time: '7:43 PM PDT',
    author: 'Eve Bouffard',
    adds: 462,
    dels: 56,
    title: 'Real episode data for the full catalog',
    bullets: [
      'The sample set replaced with real episodes across every season.',
      'Light grey placeholder art for episodes without covers yet.',
    ],
  },
  {
    version: '1.11',
    badge: 'new',
    day: '2025-10-14',
    time: '7:46 PM PDT',
    author: 'Eve Bouffard',
    adds: 114,
    dels: 20,
    title: 'Episode pagination',
    bullets: [
      'The homepage grid stays tight as the catalog grows.',
      'Season display logic reworked, and the first cut of an all-episodes page.',
    ],
  },
  {
    version: '1.12',
    badge: 'improved',
    day: '2025-10-14',
    time: '7:51 PM PDT',
    author: 'Eve Bouffard',
    adds: 9,
    dels: 9,
    title: 'Six new episode covers',
    bullets: [
      'Andy Lapsa, Chris Best, Christina Cacioppo, Emmet Shear, Jen Herbach, and Paul Gross get cover art.',
      'Buttons reordered on episode cards.',
    ],
  },
  {
    version: '1.13',
    badge: 'new',
    day: '2025-10-14',
    time: '7:54 PM PDT',
    author: 'Eve Bouffard',
    adds: 65,
    dels: 2,
    title: 'Testimonials section',
    bullets: [
      'A new testimonials section on the homepage.',
      'Surrounding sections reordered around it.',
    ],
  },
  {
    version: '1.14',
    badge: 'improved',
    day: '2025-10-14',
    time: '7:57 PM PDT',
    author: 'Eve Bouffard',
    adds: 87,
    dels: 17,
    title: 'Navigation redesigned',
    bullets: ['The nav rebuilt from scratch for clarity and mobile use.'],
  },
  {
    version: '1.15',
    badge: 'improved',
    day: '2025-10-14',
    time: '8:12 PM PDT',
    author: 'Eve Bouffard',
    adds: 94,
    dels: 40,
    title: 'Hero redesign, navbar polish',
    bullets: ['Hero section redesigned; navbar refined to match.'],
  },
  {
    version: '1.16',
    badge: 'improved',
    day: '2025-10-14',
    time: '8:27 PM PDT',
    author: 'Eve Bouffard',
    adds: 136,
    dels: 30,
    title: 'Mobile optimization pass',
    bullets: ['Another round on the hero and navbar, plus a batch of mobile-specific fixes.'],
  },
  {
    version: '1.17',
    badge: 'improved',
    day: '2025-10-19',
    time: '4:01 PM PDT',
    author: 'Eve Bouffard',
    adds: 96,
    dels: 60,
    title: 'Mobile episodes + glass play button',
    bullets: [
      'The episodes section tuned for phones.',
      'The play button gets a glass hover effect.',
    ],
  },
  {
    version: '1.18',
    badge: 'improved',
    day: '2025-10-19',
    time: '4:48 PM PDT',
    author: 'Eve Bouffard',
    adds: 187,
    dels: 203,
    title: 'Card hovers smoothed, buttons unified',
    bullets: [
      'Episode card hover effects smoothed out; button styling standardized.',
      'New host headshots and a How It Started photo set.',
    ],
  },
  {
    version: '1.19',
    badge: 'improved',
    day: '2025-10-19',
    time: '5:44 PM PDT',
    author: 'Eve Bouffard',
    adds: 230,
    dels: 175,
    title: 'Episodes page restructured',
    bullets: ['The all-episodes page now reads like a real page of the site, not a widget.'],
  },
  {
    version: '1.20',
    badge: 'fixed',
    day: '2025-10-19',
    time: '5:45 PM PDT',
    author: 'Eve Bouffard',
    adds: 10,
    dels: 3,
    title: 'Episodes page scroll position',
    bullets: ['The page opens at the top instead of mid-scroll; grey background removed.'],
  },
  {
    version: '1.21',
    badge: 'new',
    day: '2025-10-19',
    time: '5:47 PM PDT',
    author: 'Eve Bouffard',
    adds: 51,
    dels: 7,
    title: 'Season filter pills',
    bullets: ['Filter pills on the episodes page — jump straight to any season.'],
  },
  {
    version: '1.22',
    badge: 'improved',
    day: '2025-10-19',
    time: '5:47 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: 'Hero height on mobile',
    bullets: ['Hero section height tuned for small screens.'],
  },
  {
    version: '1.23',
    badge: 'fixed',
    day: '2025-10-19',
    time: '5:49 PM PDT',
    author: 'Eve Bouffard',
    adds: 3,
    dels: 8,
    title: 'TypeScript build errors',
    bullets: ['Build errors squashed — the build is green again.'],
  },
  {
    version: '1.24',
    badge: 'new',
    day: '2025-10-19',
    time: '5:59 PM PDT',
    author: 'Eve Bouffard',
    adds: 43,
    dels: 9,
    title: 'Responsive hero image',
    bullets: ['The hero now uses a picture element with a dedicated mobile variant.'],
  },
  {
    version: '1.25',
    badge: 'improved',
    day: '2025-10-19',
    time: '6:21 PM PDT',
    author: 'Eve Bouffard',
    adds: 57,
    dels: 56,
    title: 'Navbar contrast, mobile hero layout',
    bullets: [
      'Navbar contrast bumped for readability.',
      'Mobile hero layout reworked — the SVG variant did not survive.',
    ],
  },
  {
    version: '1.26',
    badge: 'improved',
    day: '2025-10-19',
    time: '6:30 PM PDT',
    author: 'Eve Bouffard',
    adds: 335,
    dels: 243,
    title: 'Episode links audited',
    bullets: [
      'Every episode link checked and updated in the data file.',
      'Listen button hover effects polished.',
    ],
  },
  {
    version: '1.27',
    badge: 'improved',
    day: '2025-10-20',
    time: '1:17 PM PDT',
    author: 'Eve Bouffard',
    adds: 73,
    dels: 11,
    title: 'Solid colors, hero-aware navbar',
    bullets: [
      'The navbar goes solid and knows when it is over the hero.',
      'Hero description bottom-aligned.',
    ],
  },
  {
    version: '1.28',
    badge: 'improved',
    day: '2025-10-20',
    time: '2:10 PM PDT',
    author: 'Eve Bouffard',
    adds: 191,
    dels: 43,
    title: 'Episodes page: raspberry hero',
    bullets: [
      'Solid raspberry hero, consistent navbar, and larger filter pills on the episodes page.',
      'Image placeholders while covers load; X logo added.',
    ],
  },
  {
    version: '1.29',
    badge: 'improved',
    day: '2025-10-20',
    time: '2:14 PM PDT',
    author: 'Eve Bouffard',
    adds: 4,
    dels: 4,
    title: 'Headers switch to Inter',
    bullets: ['Clash Display swapped for Inter across headers, CSS, and the Tailwind config.'],
  },
  {
    version: '1.30',
    badge: 'fixed',
    day: '2025-10-20',
    time: '2:58 PM PDT',
    author: 'Eve Bouffard',
    adds: 13,
    dels: 18,
    title: 'Font loading',
    bullets: ['Font loading fixed, with more mobile responsiveness tweaks.'],
  },
  {
    version: '1.31',
    badge: 'fixed',
    day: '2025-10-20',
    time: '4:17 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 0,
    title: 'Deploy nudge',
    bullets: ['A one-line comment to trigger a fresh deployment.'],
  },
  {
    version: '1.32',
    badge: 'fixed',
    day: '2025-10-20',
    time: '4:18 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 3,
    title: 'Unused variable failing the build',
    bullets: ['Removed an unused variable that was breaking the TypeScript build.'],
  },
  {
    version: '1.33',
    badge: 'fixed',
    day: '2025-10-20',
    time: '4:28 PM PDT',
    author: 'Eve Bouffard',
    adds: 4,
    dels: 5,
    title: 'Mobile font rendering',
    bullets: ['Clash Display fully replaced with Inter to fix rendering on mobile.'],
  },
  {
    version: '1.34',
    badge: 'improved',
    day: '2025-10-24',
    time: '4:57 PM PDT',
    author: 'Eve Bouffard',
    adds: 5,
    dels: 4,
    title: 'Clash Display returns',
    bullets: ['Clash Display restored as the primary typeface, with Inter as fallback.'],
  },
  {
    version: '1.35',
    badge: 'improved',
    day: '2025-10-24',
    time: '5:37 PM PDT',
    author: 'Eve Bouffard',
    adds: 187,
    dels: 176,
    title: 'Titles and descriptions rewritten',
    bullets: ['Episode titles and descriptions updated across all seasons.'],
  },
  {
    version: '1.36',
    badge: 'improved',
    day: '2025-10-24',
    time: '5:44 PM PDT',
    author: 'Eve Bouffard',
    adds: 27,
    dels: 32,
    title: 'Navbar redesign, centered hero',
    bullets: ['Navbar redesigned once more; hero content centered.'],
  },
  {
    version: '1.37',
    badge: 'improved',
    day: '2025-10-27',
    time: '5:01 PM PDT',
    author: 'Eve Bouffard',
    adds: 25,
    dels: 41,
    title: 'Cleaner homepage cards',
    bullets: [
      'Episode descriptions dropped from homepage cards for a cleaner grid.',
      'Founder Mode titles refreshed.',
    ],
  },
  {
    version: '1.38',
    badge: 'improved',
    day: '2025-10-27',
    time: '5:03 PM PDT',
    author: 'Eve Bouffard',
    adds: 11,
    dels: 11,
    title: 'Founder Mode prefix removed',
    bullets: ["The 'Founder Mode:' prefix removed from episode card titles."],
  },
  {
    version: '1.39',
    badge: 'improved',
    day: '2025-10-27',
    time: '5:03 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: 'Bigger episode titles',
    bullets: ['Episode titles bumped up a size on the all-episodes page.'],
  },
  {
    version: '1.40',
    badge: 'improved',
    day: '2025-10-27',
    time: '5:06 PM PDT',
    author: 'Eve Bouffard',
    adds: 5,
    dels: 6,
    title: 'Borders out, dividers in',
    bullets: ['All-episodes cards lose their borders and drop shadows in favor of clean dividers.'],
  },
  {
    version: '1.41',
    badge: 'fixed',
    day: '2025-10-27',
    time: '5:43 PM PDT',
    author: 'Eve Bouffard',
    adds: 26,
    dels: 24,
    title: 'Navigation styling',
    bullets: ['Navigation styling fixes, and Clash Display added where it was missing.'],
  },
  {
    version: '1.42',
    badge: 'new',
    day: '2025-10-27',
    time: '5:48 PM PDT',
    author: 'Eve Bouffard',
    adds: 12,
    dels: 2,
    title: 'SPA routing on Vercel',
    bullets: ['Deep links like /episodes now resolve instead of 404ing.'],
  },
  {
    version: '1.43',
    badge: 'improved',
    day: '2025-10-27',
    time: '7:04 PM PDT',
    author: 'Eve Bouffard',
    adds: 2,
    dels: 2,
    title: 'How It Started photo swap',
    bullets: ['Now featuring Carolynn and Jessica at a conference (sorry, Steve Huffman).'],
  },
  {
    version: '1.44',
    badge: 'new',
    day: '2025-12-10',
    time: '2:20 AM PST',
    author: 'Eve Bouffard',
    adds: 60,
    dels: 28,
    title: 'Blake Scholl joins the catalog',
    bullets: [
      'The Boom Supersonic founder lands in the episode list.',
      'YouTube links in the navigation, and default cover art for episodes without one.',
    ],
  },
  {
    version: '1.45',
    badge: 'improved',
    day: '2025-12-10',
    time: '2:26 AM PST',
    author: 'Eve Bouffard',
    adds: 13,
    dels: 13,
    title: 'Unused images removed',
    bullets: ['Old unused episode images deleted; display styling tidied.'],
  },
  {
    version: '1.46',
    badge: 'improved',
    day: '2025-12-10',
    time: '2:34 AM PST',
    author: 'Eve Bouffard',
    adds: 19,
    dels: 19,
    title: 'Covers get their own directory',
    bullets: [
      'Cover images reorganized into episode-covers/.',
      'Missing art filled in — Brian Chesky, Garry Tan, Drew Houston, and more.',
    ],
  },
  {
    version: '1.47',
    badge: 'fixed',
    day: '2025-12-10',
    time: '2:40 AM PST',
    author: 'Eve Bouffard',
    adds: 5,
    dels: 3,
    title: 'CSS properties',
    bullets: ['Standard line-clamp added; hero border-radius removed on mobile.'],
  },
  {
    version: '1.48',
    badge: 'fixed',
    day: '2025-12-10',
    time: '9:52 AM PST',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: "Carolynn's title",
    bullets: ["Carolynn's title corrected in the hosts section."],
  },
  {
    version: '1.49',
    badge: 'new',
    day: '2026-02-20',
    time: '2:48 PM PST',
    author: 'Eve Bouffard',
    adds: 382,
    dels: 125,
    title: 'Season 5 arrives',
    bullets: [
      'New episodes: David Kirtley, Jared Friedman, Kashish Gupta, Spenser Skates, and Tom Blomfield.',
      'The full catalog reordered and episode data refreshed.',
    ],
  },
  {
    version: '1.50',
    badge: 'improved',
    day: '2026-02-20',
    time: '2:49 PM PST',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: 'Kashish Gupta description',
    bullets: ['The Kashish Gupta episode gets its description.'],
  },
  {
    version: '1.51',
    badge: 'new',
    day: '2026-02-21',
    time: '9:42 PM PST',
    author: 'Eve Bouffard',
    adds: 23,
    dels: 19,
    title: 'First transcripts published',
    bullets: [
      'PDF transcripts for Christina Cacioppo, Spenser Skates, and Tom Blomfield.',
      'Blake Scholl moved to his right place in the order.',
    ],
  },
  {
    version: '1.52',
    badge: 'new',
    day: '2026-03-01',
    time: '2:39 AM PST',
    author: 'Eve Bouffard',
    adds: 46,
    dels: 3,
    title: 'Ron Conway Special Series',
    bullets: ['A dedicated Ron Conway series section debuts on the homepage.'],
  },
  {
    version: '1.53',
    badge: 'new',
    day: '2026-03-06',
    time: '8:00 AM PST',
    author: 'Eve Bouffard',
    adds: 14,
    dels: 0,
    title: 'Peter Reinhardt joins Season 5',
    bullets: ['The Segment founder lands in the catalog, transcript included.'],
  },
  {
    version: '1.54',
    badge: 'new',
    day: '2026-03-06',
    time: '8:01 AM PST',
    author: 'Eve Bouffard',
    adds: 0,
    dels: 0,
    title: 'Peter Reinhardt cover art',
    bullets: ['Cover image for the Peter Reinhardt episode.'],
  },
  {
    version: '1.55',
    badge: 'new',
    day: '2026-03-19',
    time: '11:00 AM PDT',
    author: 'Eve Bouffard',
    adds: 14,
    dels: 0,
    title: 'Paul Graham joins Season 5',
    bullets: ['PG sits down with Jessica and Carolynn — with transcript.'],
  },
  {
    version: '1.56',
    badge: 'new',
    day: '2026-04-28',
    time: '8:25 AM PDT',
    author: 'Eve Bouffard',
    adds: 13,
    dels: 0,
    title: 'Justin Kan joins Season 5',
    bullets: [
      'The Twitch co-founder lands in the catalog.',
      'First change to arrive through a pull request.',
    ],
  },
  {
    version: '1.57',
    badge: 'new',
    day: '2026-04-28',
    time: '11:45 AM PDT',
    author: 'Eve Bouffard',
    adds: 2,
    dels: 1,
    title: 'Justin Kan transcript',
    bullets: ['Full episode transcript published as PDF.'],
  },
  {
    version: '1.58',
    badge: 'new',
    day: '2026-04-28',
    time: '3:15 PM PDT',
    author: 'Eve Bouffard',
    adds: 0,
    dels: 0,
    title: 'Justin Kan cover art',
    bullets: ['Cover image for the Justin Kan episode.'],
  },
  {
    version: '1.59',
    badge: 'new',
    day: '2026-04-28',
    time: '3:23 PM PDT',
    author: 'Eve Bouffard',
    adds: 16,
    dels: 2,
    title: 'Ron Conway returns: the SVB episode',
    bullets: [
      'The SVB collapse episode joins Season 5, with transcript.',
      'Ron Conway episode titles unified across the series.',
    ],
  },
  {
    version: '1.60',
    badge: 'improved',
    day: '2026-04-28',
    time: '3:24 PM PDT',
    author: 'Eve Bouffard',
    adds: 5,
    dels: 5,
    title: 'Topic subtitles for Ron Conway',
    bullets: ['Every Ron Conway episode title now carries a topic subtitle.'],
  },
  {
    version: '1.61',
    badge: 'improved',
    day: '2026-04-28',
    time: '3:25 PM PDT',
    author: 'Eve Bouffard',
    adds: 1,
    dels: 1,
    title: 'Descriptive SVB title in Latest Episodes',
    bullets: ['Latest Episodes now shows the descriptive Ron Conway SVB title.'],
  },
  {
    version: '1.62',
    badge: 'new',
    day: '2026-04-28',
    time: '3:27 PM PDT',
    author: 'Eve Bouffard',
    adds: 150,
    dels: 1,
    title: 'Ron Conway series page',
    bullets: ['A dedicated page for the whole series, live at /ron-conway.'],
  },
  {
    version: '1.63',
    badge: 'new',
    day: '2026-04-28',
    time: '7:07 PM PDT',
    author: 'Eve Bouffard',
    adds: 86,
    dels: 2,
    title: 'Ron Conway Part 4 + link previews',
    bullets: [
      'Ron Conway Part 4 transcript published.',
      'Open Graph image and a /og preview page — shared links now unfurl properly.',
    ],
  },
  {
    version: '1.64',
    badge: 'fixed',
    day: '2026-04-28',
    time: '7:12 PM PDT',
    author: 'Eve Bouffard',
    adds: 21,
    dels: 1,
    title: 'Hero title overlap on mobile',
    bullets: ['The hero title no longer overlaps or overflows on small screens.'],
  },
  {
    version: '1.65',
    badge: 'improved',
    day: '2026-04-28',
    time: '7:15 PM PDT',
    author: 'Eve Bouffard',
    adds: 5,
    dels: 0,
    title: 'Ron Conway Series in the footer',
    bullets: ["The series linked from the footer's Quick Links."],
  },
  {
    version: '1.66',
    badge: 'new',
    day: '2026-05-21',
    time: '11:23 AM PDT',
    author: 'Eve Bouffard',
    adds: 14,
    dels: 0,
    title: 'John Coogan joins Season 5',
    bullets: ['The TBPN co-host lands in the catalog, transcript included.'],
  },
  {
    version: '1.67',
    badge: 'new',
    day: '2026-05-21',
    time: '11:26 AM PDT',
    author: 'Eve Bouffard',
    adds: 0,
    dels: 0,
    title: 'John Coogan cover art',
    bullets: ['Cover image for the John Coogan episode.'],
  },
  {
    version: '1.68',
    badge: 'new',
    day: '2026-07-29',
    time: '3:25 PM PDT',
    author: 'Eve Bouffard',
    adds: 39,
    dels: 38,
    title: 'Every episode gets a transcript',
    bullets: [
      '38 PDF transcripts across Seasons 1–5 — Brian Chesky, Garry Tan, Paul Buchheit, Tony Xu, Brian Armstrong, the Stripe episode, and more.',
      'Episode data updated so every transcript is served from the site itself.',
    ],
  },
  {
    version: '1.69',
    badge: 'new',
    day: '2026-07-29',
    time: '3:41 PM PDT',
    author: 'Chris Hall',
    adds: 1356,
    dels: 1,
    title: 'A secret changelog',
    bullets: [
      "You're looking at it: a hidden page at /changelog documenting every release since day one.",
      "Live in-development clock, line-count bar, and a commit heatmap — all generated from the site's real git history.",
      'Not linked from anywhere. If you found this, you know.',
    ],
  },
  {
    version: '1.70',
    badge: 'improved',
    day: '2026-07-29',
    time: '3:55 PM PDT',
    author: 'Chris Hall',
    adds: 49,
    dels: 5,
    title: 'The changelog learns about itself',
    bullets: [
      "Today's releases added — the transcript drop and this very page.",
      'Totals, heatmap, and release count brought up to date.',
    ],
  },
  {
    version: '1.71',
    badge: 'improved',
    day: '2026-07-29',
    time: '4:20 PM PDT',
    author: 'Chris Hall',
    adds: 62,
    dels: 404,
    title: 'The changelog goes on brand',
    bullets: [
      'Redesigned to match the rest of the site: red hero, Clash Display headlines, and a clean divider list on white.',
      'The imported dashboard look — heatmap, live clock, line counts — retires.',
    ],
  },
];
