export interface Episode {
  id: string;
  name: string;
  title: string;
  description: string;
  season: number;
  image: string;
  imagePosition: 'top' | 'center';
  seasonLabel?: string;
  hasTranscript: boolean;
  hasAudio: boolean;
  audioUrl?: string;
  transcriptUrl?: string;
}

export const episodesData: Episode[] = [
  // Founder Mode Episodes (Latest)
  {
    id: "sajith-wickramasekara",
    name: "Sajith Wickramasekara, Founder & CEO, Benchling",
    title: "Founder Mode: Sajith Wickramasekara, Founder & CEO, Benchling",
    description: "In today's Social Radars, we talk to Sajith Wickramasekara of Benchling. For Sajith, founder mode means a pervasive feeling of responsibility for everything at the company. Nothing can be bad at Benchling.",
    season: 4,
    image: "/images/episodes/Sajith-wickramasekara.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZjI2MjY4NjAtZWEwNi00MjBiLWJjNjgtYjBhNGFhYmM1NGVm",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-x-Sajith-Wickramasekara.pdf"
  },
  {
    id: "jen-herbach",
    name: "Jen Herbach, Founder & CEO, Adventris Pharmaceuticals",
    title: "Founder Mode: Jen Herbach, Founder & CEO, Adventris Pharmaceuticals",
    description: "In the latest Social Radars, we talk to Jen Herbach of Adventris, which is working on a cancer vaccine. She was in the audience of Brian Chesky's famous founder mode talk, and immediately went home and started changing things.",
    season: 4,
    image: "/images/episode-covers/jen-herbach.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/Mjg4N2MyMWUtNTdhZC00MTYwLTk0M2MtYWM0NDI3ZDM2NGE2",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Jen-Herbach.pdf"
  },
  {
    id: "andy-lapsa",
    name: "Andy Lapsa, Founder & CEO, Stoke Space",
    title: "Founder Mode: Andy Lapsa, Founder & CEO, Stoke Space",
    description: "In this episode we talk to Andy Lapsa of Stoke Space. This startup is literally doing rocket science, because they're building fully reusable rockets. Anyone who meets Andy is struck by the depth of his expertise, and in this company that's what founder mode means: a deep understanding of all the engineering problems.",
    season: 4,
    image: "/images/episode-covers/andy-lapsa.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZDMwMTlkOGItZDhmYi00OTYxLWIzZTItNDRjZmQyYjQwNDdj?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Andy-Lapsa.pdf"
  },
  {
    id: "emmett-shear-founder-mode",
    name: "Emmett Shear, Founder, Softmax & Twitch",
    title: "Founder Mode: Emmett Shear, Founder, Softmax & Twitch",
    description: "In this Social Radars episode we talk to Emmett Shear, who told us about an interesting founder mode technique he developed when he was running Twitch. He wanted people there to be able to answer the question \"What would Emmett do?\" and he found the best way to ensure this was via the weekly all-hands, which he'd spend hours preparing for.",
    season: 4,
    image: "/images/episode-covers/emmet-shear.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZDhkZGJjMjYtMWI0MS00ZmI0LWI5ZjctZGE1Mjc3OTg5ODQ0",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-X-Founder-Mode-Emmett-Shear-97s4.pdf"
  },
  {
    id: "christina-cacioppo",
    name: "Christina Cacioppo, Founder & CEO, Vanta",
    title: "Founder Mode: Christina Cacioppo, Founder & CEO, Vanta",
    description: "In today's episode, Christina Cacioppo gives us her take on founder mode, which is becoming more important now that Vanta has 1,000 employees around the world. She told us about a new variant of the idea: founder mode in fundraising. Christina delayed fundraising till after Vanta hit $100m ARR, which caused some investors to dismiss her, but she ended up net ahead.",
    season: 4,
    image: "/images/episode-covers/christina-cacioppo.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/NzQ0OGE3N2MtYmQ3Yy00ZWY3LTk0ZmQtN2IwZTZkMmU3NmQx?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Christina-Cacioppo.pdf"
  },
  {
    id: "paul-gross",
    name: "Paul Gross, Founder & CEO of Remora Carbon",
    title: "Founder Mode: Paul Gross, Founder & CEO of Remora Carbon",
    description: "In this episode we talk to Paul Gross of Remora Carbon, a startup that does carbon capture right out of the exhausts of trucks and trains. Paul has a unique take on founder mode: once a quarter he decides what the three top risks to the company are, and for that quarter, those three things, whatever they are, are the main things he works on.",
    season: 4,
    image: "/images/episode-covers/paul-gross.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/MjZiOTI2ODItMjNhYi00NjFiLTk3MTYtZjZhOTAzZTc3MzI1?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Paul-Gross.pdf"
  },
  {
    id: "chris-best",
    name: "Chris Best, Founder & CEO, Substack",
    title: "Founder Mode: Chris Best, Founder & CEO, Substack",
    description: "In this episode, taped in front of a live audience, Chris Best tells us the story of Substack. He reminisces about his adventures with Elon Musk, and explains how he persisted in bringing to market a component of Substack that he knew was critical to their vision, even though any non-founder CEO would have killed it after years without any growth.",
    season: 4,
    image: "/images/episode-covers/chris-best.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZmNhMWUwMTYtNzUyNS00MDU2LWJmZGMtNmJjZjdmZWMwYjhl",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Chris-Best.pdf"
  },
  {
    id: "jake-heller",
    name: "Jake Heller, Founder & CEO, Casetext",
    title: "Founder Mode: Jake Heller, Founder & CEO, Casetext",
    description: "In this episode, Jake Heller talks about how he and his cofounder discovered the perfect product in a weekend of intense experimentation after GPT4 was released, and then changed the whole direction of the company. This was a classic case of founder mode, because Casetext was already 9 years old at that point and it was hard to convince everyone to change course.",
    season: 4,
    image: "/images/episode-covers/jake-heller.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ODlkZDgyNGUtOTM1My00MzEzLTk4ODMtNzdlMDU2NDc1YWFl?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/Jake-Heller-Transcript-Founder-Modedocx.pdf"
  },
  {
    id: "paul-graham-founder-mode",
    name: "Paul Graham, Founder, Y Combinator",
    title: "Founder Mode: Paul Graham, Founder, Y Combinator",
    description: "Paul Graham talks about how the concept of founder mode arose from Brian Chesky's famous talk in 2024, what it means, and the latest things he's observed in the startup world.",
    season: 4,
    image: "/images/episode-covers/paul-graham.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/N2M5ZGU5MzYtODAyYS00NDUzLThjMTItYTI1ZDA3YmIwZWIz",
    transcriptUrl: "https://www.thesocialradars.com/s/PG-Founder-Mode-Transcript-docx.pdf"
  },
  {
    id: "garry-tan-founder-mode",
    name: "Garry Tan, President & CEO, Y Combinator",
    title: "Founder Mode: Garry Tan, President & CEO, Y Combinator",
    description: "We spoke with YC president & CEO Garry Tan about the Founder Mode event he organized for YC alumni. He talks about why founder mode matters and how the concept is evolving the the age of AI.",
    season: 4,
    image: "/images/episode-covers/garry-tan.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/MjhkN2ExMTMtYzBkMy00ZjgyLWI5ZmEtYjViMTAyYTQ2MjM2",
    transcriptUrl: "https://www.thesocialradars.com/s/GT-Founder-Mode-Transcriptdocx.pdf"
  },
  {
    id: "brian-chesky-founder-mode",
    name: "Brian Chesky, Founder & CEO, Airbnb",
    title: "Founder Mode: Brian Chesky, Founder & CEO, Airbnb",
    description: "At YC's first Founder Mode event, we talk with Brian Chesky, whose legendary talk last year was the origin of the concept. Unless you were one of the lucky founders in that audience, this interview is probably the closest you can get to experiencing it.",
    season: 4,
    image: "/images/episode-covers/brian-chesky.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/Yjg5MDc4N2UtNzgzNy00MGE2LWI1ZjMtMzk4ZjkyNzk5MzBm",
    transcriptUrl: "https://www.thesocialradars.com/s/Brian-Chesky-Tscript.pdf"
  },
  {
    id: "ron-conway-part-3",
    name: "Ron Conway",
    title: "Ron Conway, Founder, SV Angel Part 3",
    description: "In Part 3 of our conversation with Ron Conway, he takes us behind the scenes at early Google. Ron was involved with Google almost from the start; he and Ram Shriram arranged their Series A round. So if you want to know what a really, really big success looked like at the beginning, this is the episode for you.",
    season: 4,
    image: "/images/episode-covers/ron-conway.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/0e7660517b93fb5155f40762a27bed0c",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Ron-Conway-Part-3.pdf"
  },
  {
    id: "drew-houston",
    name: "Drew Houston",
    title: "Drew Houston, Founder & CEO of Dropbox",
    description: "In today's episode we talk with Drew Houston, founder and CEO of Dropbox. We've known Drew for a long time (YC funded Dropbox in 2007) and he's extremely candid about the many challenges he faced, and overcame, in the journey from building something that solved his own problem to serving as an essential part of the foundation of today's tech infrastructure. If you want to understand what it takes to be the CEO of a public company, this episode is for you.",
    season: 4,
    image: "/images/episode-covers/drew-houston.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/05a20f76e68270895b738479a57e4076",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Drew-Houston.pdf"
  },
  {
    id: "sam-altman",
    name: "Sam Altman",
    title: "Sam Altman, CEO of OpenAI",
    description: "Today we catch up with Sam Altman, Founder and CEO of OpenAI. Sam was in Y Combinator's first batch in 2005 and later returned as YC's president from 2014 to 2019, so he's one of the people in Silicon Valley that we know best. In this episode we cover his whole journey from Stanford sophomore to one of the most influential figures in tech.",
    season: 4,
    image: "/images/episode-covers/sam-altman.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/c83729ec6f6bfb9381455eea8b43108c",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Sam-Altman.pdf"
  },
  {
    id: "eric-migicovsky",
    name: "Eric Migicovsky",
    title: "Eric Migocovsky, Founder, Pebble & Beeper",
    description: "In today's episode Eric Migicovsky, the founder of Pebble and Beeper, shares the journey of building one of the first smartwatches. The Pebble watch made history as Kickstarter's most-funded project at the time, raising $10.3 million. What happened next showed how difficult it was to build a hardware startup in the 2010s, even if you did almost everything right.",
    season: 4,
    image: "/images/episode-covers/eric-migicovsky.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/9652aba799352d86c1dc9b1de9684f8c",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Eric-Migicovsky.pdf"
  },
  {
    id: "alexandr-wang",
    name: "Alexandr Wang",
    title: "Alexandr Wang, Founder and CEO of Scale AI",
    description: "In today's episode we go down into the engine room of the AI Revolution with Scale AI founder Alexandr Wang. Since 2016 Scale has been supplying training data to most of the top AI models. In fact there's probably no one with a better overall view of the field than Alexandr.",
    season: 4,
    image: "/images/episodes/alexandr-wang.jpg",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/189cdd0b906fb957fa8d613c271cc8bb",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Alexandr-Wang.pdf"
  },
  {
    id: "harj-taggar",
    name: "Harj Taggar",
    title: "Harj Taggar, Partner, Y Combinator",
    description: "Today we catch up with Harj Taggar, who knows as much about startups as anyone of his generation. YC funded two of his startups, Auctomatic in 2007 and Triplebyte in 2015. In between them he was the first partner we hired besides the founders, and now he's a YC partner again. Among other things he happened to have a front row seat for the Damore controversy in 2017, and is one of the few people who know just how extreme things got in those days.",
    season: 4,
    image: "/images/episode-covers/harj-taggar.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/95b677d9edf6d1bffce47712320a0f27",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Harj-Taggar.pdf"
  },
  {
    id: "gusto-founders",
    name: "Gusto Co-Founders",
    title: "Gusto Co-Founders: Josh Reeves, Edward Kim & Tomer London",
    description: "In today's episode, we chat with all three of the Gusto founders: Josh Reeves, Eddie Kim, and Tomer London. Gusto is a payroll and employee benefits company that YC funded in 2012. The striking thing about Josh, Eddie, and Tomer is their level of commitment: to their customers, their employees, and one another. It's rare to see a startup with 3 founders still being run by all 3 founders 12 years in, but these guys are special.",
    season: 4,
    image: "/images/episode-covers/gusto-founders.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/89bbacd2a49faf49e83a80447049a53e",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Gusto-Founders.pdf"
  },
  {
    id: "ron-conway-part-2",
    name: "Ron Conway",
    title: "Ron Conway, Founder, SV Angel Part 2",
    description: "In Part 2 of our conversation with legendary investor Ron Conway, we chat about how he made one of the most prescient decisions in the history of startup investing when he decided in the early 1990s to focus exclusively on investing in internet startups. It's like being a fly on the wall at the beginning of the internet boom as he takes us through shadowing Sequoia founder Don Valentine and \"living\" in Netscape's office as it took off.",
    season: 4,
    image: "/images/episode-covers/ron-conway.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/c64e600dfb5e13c9b60a713f99b404c6",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Ron-Conway-Part-2.pdf"
  },
  {
    id: "surbhi-sarna",
    name: "Surbhi Sarna",
    title: "Surbhi Sarna, Founder of nVision Medical",
    description: "In this episode, we speak with Surbhi Sarna, founder of nVision Medical, a pioneering company in women's health diagnostics. Surbhi shares her journey from experiencing a personal health scare as a teenager to founding nVision, which developed a microcatheter for the detection of ovarian cancer. nVision was acquired by Boston Scientific for $275 million in 2018. Now a Partner at Y Combinator, Surbhi discusses her transition from founder to mentor, offering insights into the challenges of healthcare innovation. Her book, Without a Doubt, was released in 2022.",
    season: 4,
    image: "/images/episode-covers/surbhi-sarna.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/956e235ffc283705e11969fe928929f9",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Surbhi-Sarna.pdf"
  },
  {
    id: "tyler-shultz-part-2",
    name: "Tyler Shultz",
    title: "Tyler Shultz, Theranos Whistleblower Part 2",
    description: "We're back with Tyler Shultz for the second part of his story: the whistleblowing. He'd resigned after noticing potential fraud within Theranos. After he spoke on background to the Wall Street Journal, Theranos retaliated with a series of legal threats, intimidation, and surveillance -- all designed to silence him. Tyler tells us about the nightmare leading up to when the news story broke, and the world found out about Theranos. (Learn more about Tyler at tyler-shultz.com.)",
    season: 4,
    image: "/images/episode-covers/tyler-shultz.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/16f0076c1bc1c949d20751a0182816cd",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Tyler-Shultz-Part-2.pdf"
  },
  {
    id: "tyler-shultz-part-1",
    name: "Tyler Shultz",
    title: "Tyler Shultz, Theranos Whistleblower Part 1",
    description: "Tyler Shultz went to work at Theranos right out of Stanford and soon noticed that things weren't as they seemed. Lots of other employees knew there was something fishy going on, but Tyler was one of a tiny handful able to resist the mesmerizing and intimidating Elizabeth Holmes and speak out about the fraud that was putting patients at risk. This podcast is a lesson for anyone who wants learn what it takes to speak out against misdeeds by powerful people. (Learn more about Tyler at tyler-shultz.com.)",
    season: 4,
    image: "/images/episode-covers/tyler-shultz.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a350809c5169e0a8ab4fc9f2cb086e27",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Tyler-Shultz-Part-1-r3nr.pdf"
  },
  {
    id: "amjad-masad-haya-odeh",
    name: "Amjad Masad & Haya Odeh",
    title: "Amjad Masad & Haya Odeh, Co-Founders of Replit",
    description: "Today we talk to Amjad Masad and Haya Odeh of Replit. They're not just co-founders but married too, and Replit is woven through their lives. Listen in as they describe their mission to bring coding to everyone.",
    season: 3,
    image: "/images/episode-covers/amjad-masad-haya-odeh.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/617f91c729ea8c28a4ecc187518ad130",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Replit.pdf"
  },
  {
    id: "ryan-petersen",
    name: "Ryan Petersen",
    title: "Ryan Petersen, Founder & CEO of Flexport",
    description: "In today's episode we chat with Ryan Petersen, Founder and CEO of Flexport, a global logistics company that Y Combinator funded in 2014. Ryan takes us on a journey from his early days importing motorcycles, through the supply chain disasters of the pandemic, to a company with thousands of employees and billions in revenue. If you want to hear about established industries being transformed by startups, this is the episode for you.",
    season: 3,
    image: "/images/episode-covers/ryan-petersen.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/82f256f49022eb7a9e7e368ccb6cb68d",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Ryan-Petersen.pdf"
  },
  {
    id: "dan-siroker",
    name: "Dan Siroker",
    title: "Dan Siroker, Co-founder of Limitless & Optimizely",
    description: "Today we catch up with Dan Siroker, co-founder of Limitless, which trains a personal AI to remember things for you. Y Combinator funded his previous company, Optimizely, in 2010, and it was acquired a decade later. But before he started Optimizely he ran the new media group within the Obama campaign, which achieved stunning results through A/B testing. In fact Optimizely was the software he wished he'd had then.",
    season: 3,
    image: "/images/episode-covers/dan-siroker.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a769c999c21539a7a7de80fc33f6aaf7",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Dan-Siroker-smcf.pdf"
  },
  {
    id: "eddy-lu",
    name: "Eddy Lu",
    title: "Eddy Lu, Co-founder & CEO of GOAT",
    description: "In today's episode we catch up with Eddy Lu, co-founder and CEO of GOAT, the fashion marketplace. GOAT represents one of the most epic pivots in Y Combinator history: they started out organizing group dinners. Founders are often told they should be \"scrappy\". Eddy and his cofounder Daishin are scrappiness personified, and that's what enabled them to bounce from idea to idea and end up on top.",
    season: 3,
    image: "/images/episode-covers/eddy-lu.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/80209983b06344ca97eea6ae6e72f334",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Eddy-Lu.pdf"
  },
  {
    id: "david-rusenko",
    name: "David Rusenko",
    title: "David Rusenko, Founder of Weebly",
    description: "David Rusenko was a college student when he applied, at the last minute, to Y Combinator in 2006. His startup, Weebly, made a web site builder. At one point they came within days of running out of money, but they survived to be acquired by Square in 2018 for $365 million. Now David runs a fund, Leap Forward Ventures, focused on climate change. He has spent his whole career in startups, and has seen close to everything that can happen.",
    season: 3,
    image: "/images/episode-covers/david-rusenko.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/b56ecb9cc9f668e9ad097434ad937167",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-David-Rusenko.pdf"
  },
  {
    id: "yin-wu",
    name: "Yin Wu",
    title: "Yin Wu, Co-Founder of Pulley",
    description: "In today's episode, we talk with Yin Wu, founder and CEO of Pulley, a cap table management system that YC funded in 2020. Yin has been founding startups since 2011 and she talks about her experiences testing startup ideas, what she's learned about persistence and determination, and why she loves having startup founders as users.",
    season: 3,
    image: "/images/episode-covers/yin-wu.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/e5072737bba8bd81d22abfac7fb809ce",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Yin-Wu-PDF-Transcript-for-Sitedocx.pdf"
  },
  {
    id: "ron-conway-s3",
    name: "Ron Conway",
    title: "Ron Conway, Founder, SV Angel",
    description: "Ron Conway has been close to the center of things for longer than anyone else in Silicon Valley, from the point when he started his career at National Semiconductor in the early '70s, to the AI conference he organized last month. He's the embodiment and the transmitter of Silicon Valley culture. He knows all the stories, usually because he was personally involved in them. In this episode we talk about what Silicon Valley was like when it was all about silicon, and how his career at Nat Semi led to working at and then running tech companies, and finally to angel investing.",
    season: 3,
    image: "/images/episode-covers/ron-conway.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/fb9d96d261aa5b545ce9271b4dbe10f0",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Ron-Conway-S3.pdf"
  },
  {
    id: "kyle-vogt",
    name: "Kyle Vogt",
    title: "Kyle Vogt, Founder of Cruise Automation",
    description: "Today we catch up with Kyle Vogt, whose self-driving car company, Cruise, was funded by Y Combinator in 2014 and acquired by GM in 2016. Before that he was a co-founder of Twitch and its predecessor, Justin.tv. Learn how his love of building hard things started at a young age, and why he's nowhere near done building yet.",
    season: 3,
    image: "/images/episode-covers/kyle-vogt.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/d44503cfd6ec667d055d026be6a98d8f",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Kyle-Vogt-S3docx.pdf"
  },
  {
    id: "yuri-sagalov",
    name: "Yuri Sagalov",
    title: "Yuri Sagalov, Co-Founder of AeroFS",
    description: "Today we are talking to Yuri Sagalov. His company AeroFS, which did enterprise file syncing and sharing, was funded by Y Combinator in summer 2010. Yuri went on to work at Y Combinator before starting his own fund, Wayfinder Ventures.",
    season: 3,
    image: "/images/episode-covers/yuri-sagalov.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a45ba4c6408c14614f7958aef26ee383",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Yuri-Sagalov-S3.pdf"
  },
  {
    id: "adora-cheung",
    name: "Adora Cheung",
    title: "Adora Cheung, Co-founder of Homejoy & Instalab",
    description: "Today we chat with Adora Cheung, Co-founder of Homejoy (YC summer 2010) and now Instalab, an at-home blood testing service that helps you optimize your health by measuring over 60 biomarkers. Our conversation is wide-ranging: from how to clean homes efficiently to how she helped defeat Trump in 2020 by getting hundreds of thousands of votes in swing states.",
    season: 2,
    image: "/images/episode-covers/adora-cheung.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/5e4444d99c7c4a232d8d2d3b1cf0b16c",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Adora-Cheungdocx.pdf"
  },
  {
    id: "trevor-blackwell",
    name: "Trevor Blackwell",
    title: "Trevor Blackwell, Co-founder Y Combinator; Founder, Anybots",
    description: "Today we have another insider episode: we're talking to Trevor Blackwell, who was my co-founder at Y Combinator. But that's not all he's done. He was also the founder of Anybots, where he created the first dynamically balancing biped robot, and also worked on Viaweb with Paul Graham and Robert Morris.",
    season: 2,
    image: "/images/episode-covers/trevor-blackwell.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/b92ce1311223d0b2b4f9489681c85c7b",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Trevor-Blackwell.pdf"
  },
  {
    id: "parker-conrad",
    name: "Parker Conrad",
    title: "Parker Conrad, Founder of Zenefits & Rippling",
    description: "Today we're talking with Parker Conrad, who founded two startups that went on to become unicorns: Zenefits in 2013, and Rippling in 2016. Parker's story is one the more dramatic ones you'll hear on this podcast. In fact this episode is two stories: his misadventures at Zenefits, and the ambitious ideas he has implemented at Rippling.",
    season: 2,
    image: "/images/episode-covers/parker-conrad.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/3ad4c8281658c6cac78f43537fcbd297",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-Parker-Conrad.pdf"
  },
  {
    id: "emmett-shear-s2",
    name: "Emmett Shear",
    title: "Emmett Shear, Co-Founder of Twitch",
    description: "Today we talk with Emmett Shear, who was in the very first YC batch in 2005 with a startup called Kiko. But you know him better as the co-founder of Twitch, which YC funded in 2007. Learn how Twitch grew from one guy walking around with a camera on his head to one of the biggest communities on the internet. It's a crazy story even by startup standards. Enjoy!",
    season: 2,
    image: "/images/episode-covers/emmett-shear.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/94ca32797e89b410b0bf15fc849e3d1e",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Emmett-Shear.pdf"
  },
  {
    id: "patrick-john-collison",
    name: "Patrick & John Collison",
    title: "Patrick & John Collison, Co-Founders of Stripe",
    description: "In this episode we catch up with Patrick and John Collison, two brothers from Ireland who founded Stripe in 2009. Since then we've watched Stripe grow from a two-man show to one of the great powers of the tech world.",
    season: 2,
    image: "/images/episode-covers/patrick-john-collison.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a54a49f4a2a444e9238d3c880d4b657c",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-Stripe-Finaldocx.pdf"
  },
  {
    id: "bill-clerico",
    name: "Bill Clerico",
    title: "Bill Clerico, Co-Founder & CEO of WePay",
    description: "Today we're talking with Bill Clerico of WePay, which Y Combinator funded in 2009. WePay was one of the first of what are now called \"FinTech\" startups. In 2017, J.P. Morgan acquired WePay for $400M. Listen in to the adventures of an early fintech pioneer.",
    season: 2,
    image: "/images/episode-covers/bill-clerico.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/4baa111152cdf47920eb28988ccbea1a",
    transcriptUrl: "https://www.thesocialradars.com/s/The-Social-Radars-x-Bill-Clerico.pdf"
  },
  {
    id: "dimitri-dadiomov",
    name: "Dimitri Dadiomov",
    title: "Dimitri Dadiomov, Co-Founder & CEO of Modern Treasury",
    description: "Today we're talking with Dimitri Dadiomov of Modern Treasury, a startup Y Combinator funded in 2018. Dimitri works in a very important world whose existence is hidden from most people: the movement of money into and out of companies. Listen in as we follow the money!",
    season: 2,
    image: "/images/episode-covers/dimitri-dadiomov.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a279dfd6dadb12957d7e9f2ea66b5174",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Dimitri-Dadiomov.pdf"
  },
  {
    id: "brian-armstrong",
    name: "Brian Armstrong",
    title: "Brian Armstrong, Co-Founder & CEO of Coinbase",
    description: "Today we're talking with Brian Armstrong of Coinbase, a startup YC funded in 2012 and is now a publicly traded company. Coinbase is truly in the middle of the exciting new world of cryptocurrency. It's particularly interesting to explore this world with Brian, who was unusually candid, even for Silicon Valley.",
    season: 2,
    image: "/images/episode-covers/brian-armstrong.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/56a6a2a137bd0d7412e9f87f5ac0085a",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Brian-Armstrong.pdf"
  },
  {
    id: "brian-chesky-s2",
    name: "Brian Chesky",
    title: "Brian Chesky, Co-Founder & CEO of Airbnb",
    description: "In this episode, we're talking once again with Brian Chesky, co-founder and CEO of Airbnb. YC funded Airbnb in 2009, when the company was at death's door. During YC we watched the founders work frantically to get growth started and turn Airbnb into the rocketship that it is today. Today we pick up where we left off in Brian's incredible story of startup survival.",
    season: 2,
    image: "/images/episode-covers/brian-chesky.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/dc532adc3b4e99a648ab8d615f7f201c",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-Brian-Chesky-Season-2.pdf"
  },
  {
    id: "edith-elliot",
    name: "Edith Elliot",
    title: "Edith Elliot, Co-Founder & CEO of Noora Health",
    description: "In this episode we talk to Edith Elliot, cofounder of the non-profit startup Noora Health. Like the best for-profit startups, Noora is relentlessly effective, but what they do with relentless effectiveness is save lives. Learn how what started as a graduate school project turned into an organization that has changed the world.",
    season: 1,
    image: "/images/episode-covers/edith-elliot.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/b26a8f0beceb60078ab9de0cb3ed6c68",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Edith-Elliot.pdf"
  },
  {
    id: "paul-graham-s1",
    name: "Paul Graham",
    title: "Paul Graham, Co-founder of Viaweb and Y Combinator",
    description: "Today, we're doing something I do every day: talking to Paul Graham, who as well as being one of the founders of Viaweb and Y Combinator is also my husband. Paul has been involved with startups since 1995; before he invented the accelerator, he invented the web app. So there's a lot of information in this episode, but it was also, as you'll see, one of the funniest.",
    season: 1,
    image: "/images/episode-covers/paul-graham.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/8d061197b65ea73dfee31672a733e1bc",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Paul-Graham.pdf"
  },
  {
    id: "brian-chesky-s1",
    name: "Brian Chesky",
    title: "Brian Chesky, Co-Founder & CEO of Airbnb",
    description: "In today's episode, we're talking with Brian Chesky, cofounder and CEO of Airbnb. YC funded Airbnb in 2009, when the company was at death's door. During YC we watched the founders work frantically to get growth started and turn Airbnb into the rocketship that it is today. Learn what it takes to come up with an idea so weird that it seems like it will never work, and then make it work.",
    season: 1,
    image: "/images/episode-covers/brian-chesky.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/df3e0c417390af992b16a946bcb5651b",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Brian-Chesky.pdf"
  },
  {
    id: "steve-huffman",
    name: "Steve Huffman",
    title: "Steve Huffman, Co-Founder & CEO of Reddit",
    description: "In this episode we walk down memory lane with Steve Huffman, co-founder and CEO of Reddit, who was in Y Combinator's very first batch of startups in 2005. In those days Steve was a programmer fresh out of UVA. He had no idea that the site he was creating would become the forum of forums, still active and growing 18 years later. Hear about Reddit's eventful early years and how they affected what it eventually became.",
    season: 1,
    image: "/images/episode-covers/steve-huffman.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/e1eed71375798a8850bbfd90b03256bc",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Steve-Huffmandocx.pdf"
  },
  {
    id: "tracy-young",
    name: "Tracy Young",
    title: "Tracy Young, Co-Founder & CEO of PlanGrid",
    description: "Today we're talking with the fabulous Tracy Young, one of the most successful female startup founders so far. Y Combinator funded her company, PlanGrid in the winter of 2012. PlanGrid revolutionized the construction industry by getting blueprints off paper and onto tablets. You'll hear about how they found their idea, how they lost a cofounder to cancer in the first few weeks of YC, how they sold the company for almost a billion dollars in 2018, and how she's now gone on to start a new startup called TigerEye, with her husband and PlanGrid cofounder, Ralph Gootee.",
    season: 1,
    image: "/images/episode-covers/tracy-young.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/tracy-young-co-founder-ceo-of-plangrid/id1677066062?app=podcast&i=1000608464843",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Tracy-Young.pdf"
  },
  {
    id: "garry-tan-s1",
    name: "Garry Tan",
    title: "Garry Tan, President & CEO of Y Combinator",
    description: "In this episode we're talking to Garry Tan, the president & CEO of Y Combinator. We go full circle with Garry as we chat about his path from turning down a job with Peter Thiel, to founding a YC-backed company in 2008, then starting his own multi-billion dollar fund in 2011, and finally returning to run Y Combinator in 2023. Garry knows about programming, design, running startups, and investing in them, so there are lessons and stories for everyone in this episode.",
    season: 1,
    image: "/images/episode-covers/garry-tan.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/tracy-young-co-founder-ceo-of-plangrid/id1677066062?app=podcast&i=1000608464843",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Garry-Tan.pdf"
  },
  {
    id: "tony-xu",
    name: "Tony Xu",
    title: "Tony Xu, Founder & CEO of Doordash",
    description: "In this episode we catch up with Tony Xu, founder and CEO of the food delivery service, DoorDash. Tony and his cofounders were students at Stanford when they first launched DoorDash as a class project. Y Combinator funded them as part of its summer batch in 2013. In this episode, Tony takes us through version 1 of their idea to what is now a public company (DASH) operating in 27 countries across the globe.",
    season: 1,
    image: "/images/episode-covers/tony-xu.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/tony-xu-founder-ceo-of-doordash/id1677066062?i=1000605766698",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Tony-Xu.pdf"
  },
  {
    id: "david-lieb",
    name: "David Lieb",
    title: "David Lieb, Creator of Google Photos",
    description: "In this episode we're talking to David Lieb, creator of Google Photos. Back in 2009, YC funded his startup, Bump Technologies, which had a cool technology where you transferred your contact info from one person to another by literally bumping phones. He'll share Bump's ups and downs as they went from business school side hustle to hot new iOS app. He'll talk about getting acquired by Google and ultimately transforming Bump into the wildly popular Google Photos. David recently came back to Y Combinator as a visiting group partner.",
    season: 1,
    image: "/images/episode-covers/david-lieb.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/david-lieb-creator-of-google-photos/id1677066062?i=1000604056053",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-David-Lieb.pdf"
  },
  {
    id: "paul-buchheit",
    name: "Paul Buchheit",
    title: "Paul Buchheit, Creator of Gmail",
    description: "In the premiere episode, Jessica and Carolynn sit down with Paul Buchheit. Paul, also known as PB, created Gmail in 2004 while he was employee number 23 at Google. They do a deep dive into the history of Gmail, including the fact that it might never have launched if it weren't for a leak to the New York Times. After Google, PB went on to found a startup called FriendFeed, which was a social media aggregator, and where the first \"like\" button was created. It was acquired by Facebook in 2009. After that, he joined Y Combinator as a partner and also became one of the most successful angel investors in Silicon Valley.",
    season: 1,
    image: "/images/episode-covers/paul-buchheit.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/the-social-radars/id1345135876?i=1000603751869",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Paul-Buccheit.pdf"
  }
];