export interface Episode {
  id: string;
  name: string;
  title: string;
  description: string;
  season: number;
  image: string;
  imagePosition: 'top' | 'center';
  seasonLabel?: string;
  hasTranscript: boolean;
  hasAudio: boolean;
  audioUrl?: string;
  transcriptUrl?: string;
}

export const episodesData: Episode[] = [
  // Founder Mode Episodes (Latest)
  {
    id: "sajith-wickramasekara",
    name: "Sajith Wickramasekara",
    title: "Founder & CEO, Benchling",
    description: "Sajith Wickramasekara discusses building Benchling, the leading platform for life sciences R&D.",
    season: 4,
    image: "/images/episodes/Sajith-wickramasekara.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZjI2MjY4NjAtZWEwNi00MjBiLWJjNjgtYjBhNGFhYmM1NGVm",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-x-Sajith-Wickramasekara.pdf"
  },
  {
    id: "jen-herbach",
    name: "Jen Herbach",
    title: "Founder & CEO, Adventris Pharmaceuticals",
    description: "In the latest Social Radars, we talk to Jen Herbach of Adventris, which is working on a cancer vaccine. She was in the audience of Brian Chesky's famous founder mode talk, and immediately went home and started changing things.",
    season: 4,
    image: "/images/episode-covers/jen-herbach.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/Mjg4N2MyMWUtNTdhZC00MTYwLTk0M2MtYWM0NDI3ZDM2NGE2",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Jen-Herbach.pdf"
  },
  {
    id: "andy-lapsa",
    name: "Andy Lapsa",
    title: "Founder & CEO, Stoke Space",
    description: "In this episode we talk to Andy Lapsa of Stoke Space. This startup is literally doing rocket science, because they're building fully reusable rockets. Anyone who meets Andy is struck by the depth of his expertise, and in this company that's what founder mode means: a deep understanding of all the engineering problems.",
    season: 4,
    image: "/images/episode-covers/andy-lapsa.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZDMwMTlkOGItZDhmYi00OTYxLWIzZTItNDRjZmQyYjQwNDdj?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Andy-Lapsa.pdf"
  },
  {
    id: "emmett-shear-founder-mode",
    name: "Emmett Shear",
    title: "Founder, Softmax & Twitch",
    description: "In this Social Radars episode we talk to Emmett Shear, who told us about an interesting founder mode technique he developed when he was running Twitch. He wanted people there to be able to answer the question \"What would Emmett do?\" and he found the best way to ensure this was via the weekly all-hands, which he'd spend hours preparing for.",
    season: 4,
    image: "/images/episode-covers/emmet-shear.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZDhkZGJjMjYtMWI0MS00ZmI0LWI5ZjctZGE1Mjc3OTg5ODQ0",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-X-Founder-Mode-Emmett-Shear-97s4.pdf"
  },
  {
    id: "christina-cacioppo",
    name: "Christina Cacioppo",
    title: "Founder & CEO, Vanta",
    description: "Christina Cacioppo discusses building Vanta, the leading security compliance platform.",
    season: 4,
    image: "/images/episode-covers/christina-cacioppo.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/NzQ0OGE3N2MtYmQ3Yy00ZWY3LTk0ZmQtN2IwZTZkMmU3NmQx?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Christina-Cacioppo.pdf"
  },
  {
    id: "paul-gross",
    name: "Paul Gross",
    title: "Founder & CEO, Remora Carbon",
    description: "Paul Gross discusses building Remora Carbon, a company focused on carbon capture technology.",
    season: 4,
    image: "/images/episode-covers/paul-gross.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/MjZiOTI2ODItMjNhYi00NjFiLTk3MTYtZjZhOTAzZTc3MzI1?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Paul-Gross.pdf"
  },
  {
    id: "chris-best",
    name: "Chris Best",
    title: "Founder & CEO, Substack",
    description: "Chris Best discusses building Substack, the platform that's revolutionizing how writers connect with their audiences.",
    season: 4,
    image: "/images/episode-covers/chris-best.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ZmNhMWUwMTYtNzUyNS00MDU2LWJmZGMtNmJjZjdmZWMwYjhl",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Founder-Mode-Chris-Best.pdf"
  },
  {
    id: "jake-heller",
    name: "Jake Heller",
    title: "Founder & CEO, Casetext",
    description: "Jake Heller discusses building Casetext, the AI-powered legal research platform.",
    season: 4,
    image: "/images/episode-covers/jake-heller.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/ODlkZDgyNGUtOTM1My00MzEzLTk4ODMtNzdlMDU2NDc1YWFl?view=apps&sort=popularity",
    transcriptUrl: "https://www.thesocialradars.com/s/Jake-Heller-Transcript-Founder-Modedocx.pdf"
  },
  {
    id: "paul-graham-founder-mode",
    name: "Paul Graham",
    title: "Founder, Y Combinator",
    description: "Paul Graham discusses the founding of Y Combinator and his insights on startup building.",
    season: 4,
    image: "/images/episode-covers/paul-graham.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/N2M5ZGU5MzYtODAyYS00NDUzLThjMTItYTI1ZDA3YmIwZWIz",
    transcriptUrl: "https://www.thesocialradars.com/s/PG-Founder-Mode-Transcript-docx.pdf"
  },
  {
    id: "garry-tan-founder-mode",
    name: "Garry Tan",
    title: "President & CEO, Y Combinator",
    description: "Garry Tan discusses his journey and insights on building successful startups.",
    season: 4,
    image: "/images/episode-covers/garry-tan.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/MjhkN2ExMTMtYzBkMy00ZjgyLWI5ZmEtYjViMTAyYTQ2MjM2",
    transcriptUrl: "https://www.thesocialradars.com/s/GT-Founder-Mode-Transcriptdocx.pdf"
  },
  {
    id: "brian-chesky-founder-mode",
    name: "Brian Chesky",
    title: "Founder & CEO, Airbnb",
    description: "Brian Chesky discusses the founding and growth of Airbnb, sharing insights on building a global platform.",
    season: 4,
    image: "/images/episode-covers/brian-chesky.png",
    imagePosition: "center",
    seasonLabel: "Founder Mode",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/Yjg5MDc4N2UtNzgzNy00MGE2LWI1ZjMtMzk4ZjkyNzk5MzBm",
    transcriptUrl: "https://www.thesocialradars.com/s/Brian-Chesky-Tscript.pdf"
  },
  {
    id: "ron-conway-part-3",
    name: "Ron Conway",
    title: "Founder, SV Angel",
    description: "Ron Conway discusses his investment philosophy and insights from decades of angel investing.",
    season: 3,
    image: "/images/episode-covers/ron-conway.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/0e7660517b93fb5155f40762a27bed0c",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Ron-Conway-Part-3.pdf"
  },
  {
    id: "drew-houston",
    name: "Drew Houston",
    title: "Founder & CEO, Dropbox",
    description: "Drew Houston discusses building Dropbox and the challenges of scaling a file storage platform.",
    season: 3,
    image: "/images/episode-covers/drew-houston.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/05a20f76e68270895b738479a57e4076",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Drew-Houston.pdf"
  },
  {
    id: "sam-altman",
    name: "Sam Altman",
    title: "Founder & CEO, OpenAI",
    description: "Sam Altman discusses the founding of OpenAI and the future of artificial intelligence.",
    season: 3,
    image: "/images/episode-covers/sam-altman.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/c83729ec6f6bfb9381455eea8b43108c",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Sam-Altman.pdf"
  },
  {
    id: "eric-migicovsky",
    name: "Eric Migicovsky",
    title: "Founder, Pebble & Beeper",
    description: "Eric Migicovsky discusses building Pebble and his new venture Beeper.",
    season: 3,
    image: "/images/episode-covers/eric-migicovsky.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/9652aba799352d86c1dc9b1de9684f8c",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Eric-Migicovsky.pdf"
  },
  {
    id: "alexandr-wang",
    name: "Alexandr Wang",
    title: "Founder & CEO, Scale AI",
    description: "Alexandr Wang discusses building Scale AI and the future of AI infrastructure.",
    season: 3,
    image: "/images/episodes/alexandr-wang.jpg",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/189cdd0b906fb957fa8d613c271cc8bb",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Alexandr-Wang.pdf"
  },
  {
    id: "harj-taggar",
    name: "Harj Taggar",
    title: "Partner, Y Combinator",
    description: "Harj Taggar discusses his role at Y Combinator and insights on startup investing.",
    season: 3,
    image: "/images/episode-covers/harj-taggar.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/95b677d9edf6d1bffce47712320a0f27",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Harj-Taggar.pdf"
  },
  {
    id: "gusto-founders",
    name: "Gusto Co-Founders",
    title: "Josh Reeves, Tomer London, Edward Kim",
    description: "The Gusto co-founders discuss building the leading HR platform for small businesses.",
    season: 3,
    image: "/images/episode-covers/gusto-founders.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/89bbacd2a49faf49e83a80447049a53e",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Gusto-Founders.pdf"
  },
  {
    id: "ron-conway-part-2",
    name: "Ron Conway",
    title: "Founder, SV Angel Part 2",
    description: "Ron Conway continues his discussion on angel investing and startup ecosystem insights.",
    season: 3,
    image: "/images/episode-covers/ron-conway.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/c64e600dfb5e13c9b60a713f99b404c6",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Ron-Conway-Part-2.pdf"
  },
  {
    id: "surbhi-sarna",
    name: "Surbhi Sarna",
    title: "Founder & CEO, nVision Medical",
    description: "Surbhi Sarna discusses building nVision Medical and innovating in healthcare technology.",
    season: 3,
    image: "/images/episode-covers/surbhi-sarna.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/956e235ffc283705e11969fe928929f9",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Surbhi-Sarna.pdf"
  },
  {
    id: "tyler-shultz-part-2",
    name: "Tyler Shultz",
    title: "Theranos Whistleblower Part 2",
    description: "Tyler Shultz continues his discussion about exposing fraud at Theranos.",
    season: 3,
    image: "/images/episode-covers/tyler-shultz.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/16f0076c1bc1c949d20751a0182816cd",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Tyler-Shultz-Part-2.pdf"
  },
  {
    id: "tyler-shultz-part-1",
    name: "Tyler Shultz",
    title: "Theranos Whistleblower Part 1",
    description: "Tyler Shultz discusses his experience as a Theranos whistleblower and the importance of ethical leadership.",
    season: 3,
    image: "/images/episode-covers/tyler-shultz.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a350809c5169e0a8ab4fc9f2cb086e27",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Tyler-Shultz-Part-1-r3nr.pdf"
  },
  {
    id: "amjad-masad-haya-odeh",
    name: "Amjad Masad & Haya Odeh",
    title: "Founders, Replit",
    description: "Amjad Masad and Haya Odeh discuss building Replit, the collaborative coding platform.",
    season: 3,
    image: "/images/episode-covers/amjad-masad-haya-odeh.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/617f91c729ea8c28a4ecc187518ad130",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Replit.pdf"
  },
  {
    id: "ryan-petersen",
    name: "Ryan Petersen",
    title: "Founder & CEO, Flexport",
    description: "Ryan Petersen discusses building Flexport and revolutionizing global trade.",
    season: 3,
    image: "/images/episode-covers/ryan-petersen.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/82f256f49022eb7a9e7e368ccb6cb68d",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Ryan-Petersen.pdf"
  },
  {
    id: "dan-siroker",
    name: "Dan Siroker",
    title: "Founder & CEO, Limitless & Optimizely",
    description: "Dan Siroker discusses building Optimizely and his new venture Limitless.",
    season: 3,
    image: "/images/episode-covers/dan-siroker.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a769c999c21539a7a7de80fc33f6aaf7",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Dan-Siroker-smcf.pdf"
  },
  {
    id: "eddy-lu",
    name: "Eddy Lu",
    title: "Founder & CEO, GOAT",
    description: "Eddy Lu discusses building GOAT, the leading marketplace for authentic sneakers.",
    season: 3,
    image: "/images/episode-covers/eddy-lu.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/80209983b06344ca97eea6ae6e72f334",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Eddy-Lu.pdf"
  },
  {
    id: "david-rusenko",
    name: "David Rusenko",
    title: "Founder & CEO, Weebly",
    description: "David Rusenko discusses building Weebly and the evolution of website building tools.",
    season: 3,
    image: "/images/episode-covers/david-rusenko.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/b56ecb9cc9f668e9ad097434ad937167",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-David-Rusenko.pdf"
  },
  {
    id: "yin-wu",
    name: "Yin Wu",
    title: "Founder & CEO, Pulley",
    description: "Yin Wu discusses building Pulley, the cap table management platform for startups.",
    season: 3,
    image: "/images/episode-covers/yin-wu.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/e5072737bba8bd81d22abfac7fb809ce",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Yin-Wu-PDF-Transcript-for-Sitedocx.pdf"
  },
  {
    id: "ron-conway-s3",
    name: "Ron Conway",
    title: "Founder, SV Angel (S3)",
    description: "Ron Conway discusses his investment philosophy and insights from decades of angel investing.",
    season: 3,
    image: "/images/episode-covers/ron-conway.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/fb9d96d261aa5b545ce9271b4dbe10f0",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Ron-Conway-S3.pdf"
  },
  {
    id: "kyle-vogt",
    name: "Kyle Vogt",
    title: "Founder & CEO, Cruise Automation",
    description: "Kyle Vogt discusses building Cruise Automation and the future of autonomous vehicles.",
    season: 3,
    image: "/images/episode-covers/kyle-vogt.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/d44503cfd6ec667d055d026be6a98d8f",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-Kyle-Vogt-S3docx.pdf"
  },
  {
    id: "yuri-sagalov",
    name: "Yuri Sagalov",
    title: "Founder & CEO, AeroFS",
    description: "Yuri Sagalov discusses building AeroFS and insights on enterprise software.",
    season: 3,
    image: "/images/episode-covers/yuri-sagalov.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a45ba4c6408c14614f7958aef26ee383",
    transcriptUrl: "https://www.thesocialradars.com/s/TSR-x-Yuri-Sagalov-S3.pdf"
  },
  {
    id: "season-3-announcement",
    name: "Jessica & Carolynn",
    title: "Announce Season 3!",
    description: "Jessica Livingston and Carolynn Levy announce the launch of Season 3 of The Social Radars.",
    season: 3,
    image: "/images/episode-covers/season-3-announcement.png",
    imagePosition: "center",
    hasTranscript: false,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/2f4bceac7fb2cd7cc9c29616b7901acf"
  },
  {
    id: "adora-cheung",
    name: "Adora Cheung",
    title: "Founder, Homejoy & Instalab",
    description: "Adora Cheung discusses building Homejoy and her insights on marketplace businesses.",
    season: 2,
    image: "/images/episode-covers/adora-cheung.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/5e4444d99c7c4a232d8d2d3b1cf0b16c",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Adora-Cheungdocx.pdf"
  },
  {
    id: "trevor-blackwell",
    name: "Trevor Blackwell",
    title: "Partner, Y Combinator & Founder, Anybots",
    description: "Trevor Blackwell discusses his role at Y Combinator and building robotics company Anybots.",
    season: 2,
    image: "/images/episode-covers/trevor-blackwell.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/b92ce1311223d0b2b4f9489681c85c7b",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Trevor-Blackwell.pdf"
  },
  {
    id: "parker-conrad",
    name: "Parker Conrad",
    title: "Founder & CEO, Zenefits & Rippling",
    description: "Parker Conrad discusses building Zenefits and his new venture Rippling.",
    season: 2,
    image: "/images/episode-covers/parker-conrad.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/3ad4c8281658c6cac78f43537fcbd297",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-Parker-Conrad.pdf"
  },
  {
    id: "emmett-shear-s2",
    name: "Emmett Shear",
    title: "Founder & CEO, Twitch (S2)",
    description: "Emmett Shear discusses building Twitch and the evolution of live streaming.",
    season: 2,
    image: "/images/episode-covers/emmett-shear.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/94ca32797e89b410b0bf15fc849e3d1e",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Emmett-Shear.pdf"
  },
  {
    id: "patrick-john-collison",
    name: "Patrick & John Collison",
    title: "Founders, Stripe",
    description: "Patrick and John Collison discuss building Stripe and revolutionizing online payments.",
    season: 2,
    image: "/images/episode-covers/patrick-john-collison.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a54a49f4a2a444e9238d3c880d4b657c",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-Stripe-Finaldocx.pdf"
  },
  {
    id: "bill-clerico",
    name: "Bill Clerico",
    title: "Founder & CEO, WePay",
    description: "Bill Clerico discusses building WePay and insights on fintech innovation.",
    season: 2,
    image: "/images/episode-covers/bill-clerico.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/4baa111152cdf47920eb28988ccbea1a",
    transcriptUrl: "https://www.thesocialradars.com/s/The-Social-Radars-x-Bill-Clerico.pdf"
  },
  {
    id: "dimitri-dadiomov",
    name: "Dimitri Dadiomov",
    title: "Founder & CEO, Modern Treasury",
    description: "Dimitri Dadiomov discusses building Modern Treasury and the future of financial infrastructure.",
    season: 2,
    image: "/images/episode-covers/dimitri-dadiomov.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/a279dfd6dadb12957d7e9f2ea66b5174",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Dimitri-Dadiomov.pdf"
  },
  {
    id: "brian-armstrong",
    name: "Brian Armstrong",
    title: "Founder & CEO, Coinbase",
    description: "Brian Armstrong discusses building Coinbase and the future of cryptocurrency.",
    season: 2,
    image: "/images/episode-covers/brian-armstrong.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/56a6a2a137bd0d7412e9f87f5ac0085a",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Brian-Armstrong.pdf"
  },
  {
    id: "brian-chesky-s2",
    name: "Brian Chesky",
    title: "Founder & CEO, Airbnb (S2)",
    description: "Brian Chesky discusses the continued growth of Airbnb and lessons learned from scaling globally.",
    season: 2,
    image: "/images/episode-covers/brian-chesky.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/dc532adc3b4e99a648ab8d615f7f201c",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-Brian-Chesky-Season-2.pdf"
  },
  {
    id: "edith-elliot",
    name: "Edith Elliot",
    title: "Founder & CEO, Noora Health",
    description: "Edith Elliot discusses building Noora Health and improving healthcare outcomes in India.",
    season: 2,
    image: "/images/episode-covers/edith-elliot.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/b26a8f0beceb60078ab9de0cb3ed6c68",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Edith-Elliot.pdf"
  },
  {
    id: "paul-graham-s1",
    name: "Paul Graham",
    title: "Founder, Viaweb & YC (S1)",
    description: "Paul Graham discusses founding Viaweb, Y Combinator, and his insights on startup building.",
    season: 1,
    image: "/images/episode-covers/paul-graham.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/8d061197b65ea73dfee31672a733e1bc",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Paul-Graham.pdf"
  },
  {
    id: "brian-chesky-s1",
    name: "Brian Chesky",
    title: "Founder & CEO, Airbnb (S1)",
    description: "Brian Chesky discusses the early days of Airbnb and building a global marketplace.",
    season: 1,
    image: "/images/episode-covers/brian-chesky.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/df3e0c417390af992b16a946bcb5651b",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Brian-Chesky.pdf"
  },
  {
    id: "steve-huffman",
    name: "Steve Huffman",
    title: "Founder & CEO, Reddit",
    description: "Steve Huffman discusses building Reddit and the evolution of online communities.",
    season: 1,
    image: "/images/episode-covers/steve-huffman.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://pod.link/1677066062/episode/e1eed71375798a8850bbfd90b03256bc",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Steve-Huffmandocx.pdf"
  },
  {
    id: "tracy-young",
    name: "Tracy Young",
    title: "Founder & CEO, PlanGrid & TigerEye",
    description: "Tracy Young discusses building PlanGrid and her new venture TigerEye.",
    season: 1,
    image: "/images/episode-covers/tracy-young.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/tracy-young-co-founder-ceo-of-plangrid/id1677066062?app=podcast&i=1000608464843",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Tracy-Young.pdf"
  },
  {
    id: "garry-tan-s1",
    name: "Garry Tan",
    title: "President & CEO of YC (S1)",
    description: "Garry Tan discusses his journey and insights on building successful startups.",
    season: 1,
    image: "/images/episode-covers/garry-tan.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/tracy-young-co-founder-ceo-of-plangrid/id1677066062?app=podcast&i=1000608464843",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Garry-Tan.pdf"
  },
  {
    id: "tony-xu",
    name: "Tony Xu",
    title: "Founder & CEO, DoorDash",
    description: "Tony Xu discusses building DoorDash and revolutionizing food delivery.",
    season: 1,
    image: "/images/episode-covers/tony-xu.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/tony-xu-founder-ceo-of-doordash/id1677066062?i=1000605766698",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Tony-Xu.pdf"
  },
  {
    id: "david-lieb",
    name: "David Lieb",
    title: "Creator of Google Photos",
    description: "David Lieb discusses creating Google Photos and the future of photo management.",
    season: 1,
    image: "/images/episode-covers/david-lieb.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/david-lieb-creator-of-google-photos/id1677066062?i=1000604056053",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-David-Lieb.pdf"
  },
  {
    id: "paul-buchheit",
    name: "Paul Buchheit",
    title: "Creator of Gmail (Premiere episode)",
    description: "Paul Buchheit discusses creating Gmail and his insights on product development.",
    season: 1,
    image: "/images/episode-covers/paul-buchheit.png",
    imagePosition: "center",
    hasTranscript: true,
    hasAudio: true,
    audioUrl: "https://podcasts.apple.com/us/podcast/the-social-radars/id1345135876?i=1000603751869",
    transcriptUrl: "https://www.thesocialradars.com/s/Social-Radars-x-Paul-Buccheit.pdf"
  }
];